id: e74576dd3553404894503cc9b5ffa442
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_267-Calling_Witness_with_a_Hundred_Prostrations-v1
  language: bo
  author: ''
  volume: {}
